import { StyleSheet } from "react-native";
import colors from "../../themes/colors";

export default StyleSheet.create({
    imageHolder:{
        height:150,
        justifyContent:'center',
        alignItems:'center',
        marginHorizontal:40,
        marginTop:20,
        marginBottom:20,
        borderRadius:20,
        backgroundColor:'white',
        elevation:5,
        overflow:'hidden'
    },
    image:{
        width:'auto',
        height:200,
        marginTop:20,
        marginBottom:20
    },
    uploadPhotoButtonContainer:{
        justifyContent:'center',
        alignItems:'center'
    },
    uploadPhotoButton:{
        backgroundColor:colors.theme,
        elevation:5,
        padding:10,
        paddingHorizontal:70,
        borderRadius:50
    },
    uploadPhotoButtonText:{
        color:'white',
        fontSize:16
    },
    recipeTypePickerContainer:{
        marginHorizontal:20,
        marginTop:20,
        height:43,
        justifyContent:'center',
        backgroundColor:'white',
        borderColor:'black',
        borderWidth:1,
        borderRadius:5,
        padding:5
    },
    ingredientTitle:{
        marginHorizontal:10,
        marginTop:20,
        fontSize:16,
        color:colors.theme,
        fontWeight:'bold'
    },
    amountControlContainer:{
        marginHorizontal:25,
        marginTop:5,
        justifyContent:'space-between',
        flexDirection:'row'
    },
    procedureTitle:{
        marginHorizontal:10,
        marginTop:20,
        fontSize:16,
        color:colors.theme,
        fontWeight:'bold'
    },
    creatButtonContainer:{
        justifyContent:'center',
        alignItems:'center', 
        marginVertical:30
    },
    createButton:{
        backgroundColor:colors.theme,
        elevation:5,
        padding:10,
        paddingHorizontal:90,
        borderRadius:50
    },
    creatButtonText:{
        color:'white',
        fontSize:16
    },
})